### ISSUE TITLE
Translation 1

### ISSUE THREAD

**Issue by maryewal** [clld/vanuatuvoices#1]
#: vanuatuvoices/__init__.py:15
msgid "Languages"
msgstr "Ol lanvis"

#: vanuatuvoices/__init__.py:16
msgid "Parameters"
msgstr "Ol wod"

#: vanuatuvoices/__init__.py:17
msgid "Download"
msgstr "Daonlodem"

#: vanuatuvoices/__init__.py:18
msgid "Contact"
msgstr "Kontak"

#: vanuatuvoices/__init__.py:19
msgid "Legal"
msgstr "Imprin"

#: vanuatuvoices/__init__.py:20
msgid "Home"
msgstr "Hom"

#: vanuatuvoices/__init__.py:21
msgid "You can contact us via email at"
msgstr "--not yet translated--"

#: vanuatuvoices/__init__.py:24
msgid "Icon size"
msgstr ""

#: vanuatuvoices/__init__.py:25
msgid "Show/hide Labels"
msgstr ""

#: vanuatuvoices/__init__.py:28
msgid "Next"
msgstr "nekis"

#: vanuatuvoices/__init__.py:29
msgid "Previous"
msgstr "we i kam bifo"

#: vanuatuvoices/__init__.py:30
msgid "First"
msgstr ""

#: vanuatuvoices/__init__.py:31
msgid "Last"
msgstr ""

#: vanuatuvoices/__init__.py:32
msgid "No data available in table"
msgstr ""

#: vanuatuvoices/__init__.py:33
msgid "Showing _START_ to _END_ of _TOTAL_ entries"
msgstr ""

#: vanuatuvoices/__init__.py:34
msgid "Showing 0 to 0 of 0 entries"
msgstr ""

#: vanuatuvoices/__init__.py:35
msgid "(filtered from _MAX_ total entries)"
msgstr ""

#: vanuatuvoices/__init__.py:36
msgid "Show _MENU_ entries"
msgstr ""

#: vanuatuvoices/__init__.py:37
msgid "Loading..."
msgstr ""

#: vanuatuvoices/__init__.py:38
msgid "Processing..."
msgstr ""

#: vanuatuvoices/__init__.py:39
msgid "Search:"
msgstr ""

#: vanuatuvoices/__init__.py:40
msgid "No matching records found"
msgstr ""

**Comment by maryewal** [comment]
#: vanuatuvoices/__init__.py:15
msgid "Languages"
msgstr "Ol lanwis"

#: vanuatuvoices/__init__.py:16
msgid "Parameters"
msgstr "Ol wod"

#: vanuatuvoices/__init__.py:17
msgid "Download"
msgstr "Daonlodem"

#: vanuatuvoices/__init__.py:18
msgid "Contact"
msgstr "Kontak"

#: vanuatuvoices/__init__.py:19
msgid "Legal"
msgstr "Likol"

#: vanuatuvoices/__init__.py:20
msgid "Home"
msgstr "Hom"

#: vanuatuvoices/__init__.py:21
msgid "You can contact us via email at"
msgstr "Yu save kontaktem mifala long imel ia"

#: vanuatuvoices/__init__.py:24
msgid "Icon size"
msgstr "Saes blong aekon"

#: vanuatuvoices/__init__.py:25
msgid "Show/hide Labels"
msgstr "Soem/haedem ol Lebol"

#: vanuatuvoices/__init__.py:28
msgid "Next"
msgstr "nekis"

#: vanuatuvoices/__init__.py:29
msgid "Previous"
msgstr "we i kam bifo"

#: vanuatuvoices/__init__.py:30
msgid "First"
msgstr "Feswan"

#: vanuatuvoices/__init__.py:31
msgid "Last"
msgstr "Laswan"

#: vanuatuvoices/__init__.py:32
msgid "No data available in table"
msgstr "I nogat data i stap long tebol"

#: vanuatuvoices/__init__.py:33
msgid "Showing _START_ to _END_ of _TOTAL_ entries"
msgstr "Shoem_STAT_kasem_EN_blong_ol_FUL_infomeisen_we_wan_man_i_entarem"

#: vanuatuvoices/__init__.py:34
msgid "Showing 0 to 0 of 0 entries"
msgstr "Shoem_0_kasem_0_blong_ol_infomeisen_we_wan_man_i_entarem""

#: vanuatuvoices/__init__.py:35
msgid "(filtered from _MAX_ total entries)"
msgstr "(karemaot long_MAKS_namba blong ol infomeisen we wan man i entarem""

#: vanuatuvoices/__init__.py:36
msgid "Show _MENU_ entries"
msgstr "Soem_MENU_ol infomeisen we wan man i entarem""

#: vanuatuvoices/__init__.py:37
msgid "Loading..."
msgstr "I stap gohed"

#: vanuatuvoices/__init__.py:38
msgid "Processing..."
msgstr "I stap gohed"

#: vanuatuvoices/__init__.py:39
msgid "Search:"
msgstr "Lukaotem"

#: vanuatuvoices/__init__.py:40
msgid "No matching records found"
msgstr "Oli no faenem rikod we i semak"

**Comment by xrotwang** [comment]
For future reference: This is how translations make it into the app:
https://github.com/clld/vanuatuvoices/commit/c73d833cddace8b5dd96e4fc927eac3614bd387e#diff-48af68a1b2074900a7fc0347faeef4728bc7ee41ca2f03b065d69291052ddcba

I.e. should we add more content that needs translation (and [we already did](https://github.com/clld/vanuatuvoices/blob/c73d833cddace8b5dd96e4fc927eac3614bd387e/vanuatuvoices/locale/eo/LC_MESSAGES/clld.po#L143-L181)), this content will show up in https://github.com/clld/vanuatuvoices/blob/main/vanuatuvoices/locale/eo/LC_MESSAGES/clld.po - where translations can be added.
