### ISSUE TITLE
Email Address for Contact Page

### ISSUE THREAD

**Issue by maryewal** [clld/vanuatuvoices#10]
@xrotwang @RustyGray - just noticed we don't have an email address here: https://vanuatuvoices.clld.org/contact?__locale__=eo
 I'll ask Thomas to create a unique VV one tomorrow. If you're happy with vanuatuvoices@shh.mpg.de, we can go ahead and add that.

**Comment by RustyGray** [comment]
Yes
Russell Gray
Director, Max Planck Institute for the Evolutionary Anthropology
Head of the Department of Linguistic and Cultural Evolution
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Assistant schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://language.psy.auckland.ac.nz/
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en



On 1. Dec 2020, at 08:20, Mary Walworth <notifications@github.com<mailto:notifications@github.com>> wrote:



@xrotwang<https://github.com/xrotwang> @RustyGray<https://github.com/RustyGray> - just noticed we don't have an email address here: https://vanuatuvoices.clld.org/contact?__locale__=eo
I'll ask Thomas to create a unique VV one tomorrow. If you're happy with vanuatuvoices@shh.mpg.de<mailto:vanuatuvoices@shh.mpg.de>, we can go ahead and add that.

**Comment by maryewal** [comment]
Thomas has created the address.

**Comment by xrotwang** [comment]
See https://vanuatuvoices.clld.org/contact?__locale__=eo
