### ISSUE TITLE
"Language" to Doculect?

### ISSUE THREAD

**Issue by maryewal** [clld/vanuatuvoices#12]
Can we change "Language" to Doculect for the site titles in the English version (the Bislama doesn't need to be changed)? https://vanuatuvoices.clld.org/languages
@rustygray, what do you think about this? There is already discussion in social media picking on the use of "language". I am opposed to using "dialect".

**Comment by xrotwang** [comment]
Doculect sounds good to me - meaning "language as recorded". "Variety" might be another option, but seems to already presuppose differences between any two varieties.

**Comment by maryewal** [comment]
Yes, I agree and I generally prefer variety over dialect.  In this case, doculect is a nice plain description that avoids entering any terminology debate :)
