### ISSUE TITLE
Concept English glosses for you two and you should be switched.

### ISSUE THREAD

**Issue by maryewal** [clld/vanuatuvoices#13]
@xrotwang We need to switch the english glosses for 'you' and 'you two' - the former refers to _yufala_ and the latter to _yutufala_. If you tell me where to do this, I can make the change.

**Comment by xrotwang** [comment]
This is a [known problem](https://github.com/lexibank/vanuatuvoices/issues/8) and will be fixed upstream - then released - presumably as v1.0.1 and then imported into the web app.
