### ISSUE TITLE
Acknowledgements page

### ISSUE THREAD

**Issue by RustyGray** [clld/vanuatuvoices#4]
Can the acknowledgements be on a separate page please?

**Comment by maryewal** [comment]
Agreed. 
Also @xrotwang here are the suggested edits from my last email:
Tom Fitzpatrick contributed only audio recordings (via Murray Garde). 
Both Tom Ennever & Lana Takau also did audio post-processing. 
Lana also did the Bislama translations for the site, so we should add "Bislama Translations" for her.
Remove Benjamin Touati - he contributed to ABVD cognate coding and not to SC.
I should have "author" also listed by my name.

While I'm happy to be listed as one of the editors of the site, I definitely shouldn't be the only one. I'll leave it to @RustyGray to confirm who and in what order, but I assume it should include at least all four of us here on this email.
