### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by RustyGray** [clld/vanuatuvoices#5]
Mary can you write a one sentence project description for the homepage please for Robert to add under the title?

**Comment by maryewal** [comment]
yep, on it.  I'm assuming we want the word "diversity" in there?

**Comment by RustyGray** [comment]
Yes thanks, r.

Russell Gray
Director, Max Planck Institute for the Evolutionary Anthropology
Head of the Department of Linguistic and Cultural Evolution
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Assistant schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://language.psy.auckland.ac.nz/
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en



On 24. Nov 2020, at 12:28, Mary Walworth <notifications@github.com<mailto:notifications@github.com>> wrote:



yep, on it. I'm assuming we want the word "diversity" in there?

**Comment by maryewal** [comment]
Vanuatu Voices presents phonetically-transcribed primary recordings, from numerous villages throughout different islands, to both document and exhibit the extensive variation and unparalleled diversity of the Vanuatu languages.

OR

Vanuatu Voices presents phonetically-transcribed primary recordings of basic vocabulary as well as culturally and environmentally relevant terminology, from numerous villages throughout different islands, to both document and exhibit the extensive variation and unparalleled diversity of the Vanuatu languages.  


*When we add in cognacy, we can add something about relatedness.

**Comment by maryewal** [comment]
@xrotwang we can add in the second one. Thanks!

**Comment by RustyGray** [comment]
The former is fine for now. When we add the cultural vocabulary it can be expanded to the later. Cheers, r

Sent from my iPhone

On 28. Nov 2020, at 11:44, Mary Walworth <notifications@github.com> wrote:

﻿

@xrotwang<https://github.com/xrotwang> we can add in the second one. Thanks!

**Comment by maryewal** [comment]
@xrotwang: Vanuatu Voices presents phonetically-transcribed primary recordings, from numerous villages throughout different islands, to both document and exhibit the extensive variation and unparalleled diversity of the Vanuatu languages.
