### ISSUE TITLE
Photos of people involved

### ISSUE THREAD

**Issue by RustyGray** [clld/vanuatuvoices#8]
Can we add these  to the acknowledgement page please

**Comment by xrotwang** [comment]
@maryewal can you provide these?

**Comment by maryewal** [comment]
Yep! I think I can get everyone but Tom Fitzpatrick.

**Comment by maryewal** [comment]
Hi, so most photos are on the Sound Comparisons site - I wonder if we can just use the same ones? https://soundcomparisons.com/#/Contributors
I'll contact the remaining folks for theirs.

**Comment by maryewal** [comment]
Marie Duhamel
![mfduhamel](https://user-images.githubusercontent.com/21197058/100526092-24770e80-31c6-11eb-935c-882a58be1f0b.jpg)

**Comment by maryewal** [comment]
Lana Takau
![Lana Photo](https://user-images.githubusercontent.com/21197058/100537288-769c4c00-3227-11eb-9d43-5779da94655c.png)

**Comment by maryewal** [comment]
I saw Russell responded with a new one, but I don't see it here: https://www.shh.mpg.de/819836/original-1593523079.jpg?t=eyJ3aWR0aCI6MTQwMCwib2JqX2lkIjo4MTk4MzZ9--29c654a59d662a9dc67c963cd213872120c94b31

**Comment by RustyGray** [comment]
Bu that is it.  The link works for me. Cheers, R.

Russell Gray
Director, Max Planck Institute for the Evolutionary Anthropology
Head of the Department of Linguistic and Cultural Evolution
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Assistant schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://language.psy.auckland.ac.nz/
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en



On 29. Nov 2020, at 21:46, Mary Walworth <notifications@github.com<mailto:notifications@github.com>> wrote:



I saw Russell responded with a new one, but I don't see it here: https://www.shh.mpg.de/819836/original-1593523079.jpg?t=eyJ3aWR0aCI6MTQwMCwib2JqX2lkIjo4MTk4MzZ9--29c654a59d662a9dc67c963cd213872120c94b31

**Comment by maryewal** [comment]
Yes, sorry to be confusing. I was just moving the link to this issue.

**Comment by maryewal** [comment]
Tom Ennever
![Uploading Tom photo.png…]()

**Comment by maryewal** [comment]
Kaitip Kami
![68483588_10211424686731627_889776950099312640_n](https://user-images.githubusercontent.com/21197058/100720182-ecd2b700-33bd-11eb-9d17-68ff8e886148.jpg)

**Comment by maryewal** [comment]
Once Kaitip and Tom are added, we can close this.

**Comment by xrotwang** [comment]
Done https://vanuatuvoices.clld.org/credits?__locale__=eo
