### ISSUE TITLE
Deeper map

### ISSUE THREAD

**Issue by RustyGray** [clld/vanuatuvoices#9]
Sorry for being picky but can the map be made deeper?  seems unnaturally narrow to me.

**Comment by xrotwang** [comment]
I don't fully understand. Is this about the base layer of the map? If so, you can use the layer control on top right of the map to choose between a couple of these. Let me know which one you think most suitable. There are other criteria as well, though, when it comes to chosing a default base layer, e.g. not all layers are available at all zoom levels - and the default should be, I guess.

**Comment by RustyGray** [comment]
No, the shape. It is a narrow slit. Not the da Vinci dimensions. Cheers, Russell.

Russell Gray
Director, Max Planck Institute for the Evolutionary Anthropology
Head of the Department of Linguistic and Cultural Evolution
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Assistant schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://language.psy.auckland.ac.nz/
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en



On 26. Nov 2020, at 19:35, Robert Forkel <notifications@github.com<mailto:notifications@github.com>> wrote:



I don't fully understand. Is this about the base layer of the map? If so, you can use the layer control on top right of the map to choose between a couple of these. Let me know which one you think most suitable. There are other criteria as well, though, when it comes to chosing a default base layer, e.g. not all layers are available at all zoom levels - and the default should be, I guess.

**Comment by xrotwang** [comment]
Ah, I see. I think prescribing a certain aspect ratio is problematic considering the diversity of devices this site might be used with.
So I'd propose we simply make the map resizable, see https://jjimenezshaw.github.io/Leaflet.Control.Resizer/examples/basic.html ?

**Comment by xrotwang** [comment]
users can resize maps now.

**Comment by RustyGray** [comment]
Thanks!  Noticed that and had a play. All god.  Cheers, Russell.

Russell Gray
Director, Max Planck Institute for the Evolutionary Anthropology
Head of the Department of Linguistic and Cultural Evolution
TEL: +49-3641-68 68 01
FAX: +49-3641-68 68 68
Assistant schueck@shh.mpg.de<mailto:schueck@shh.mpg.de>
http://www.shh.mpg.de/2375/en
http://language.psy.auckland.ac.nz/
http://scholar.google.co.nz/citations?user=FzE-34YAAAAJ&hl=en



On 2. Dec 2020, at 01:19, Robert Forkel <notifications@github.com<mailto:notifications@github.com>> wrote:



users can resize maps now.
